/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BrowserVideoConvertExample {
        "framePosition": 'start' | 'middle' | 'end' | number;
        "videoSrc": string|undefined;
    }
}
declare global {
    interface HTMLBrowserVideoConvertExampleElement extends Components.BrowserVideoConvertExample, HTMLStencilElement {
    }
    var HTMLBrowserVideoConvertExampleElement: {
        prototype: HTMLBrowserVideoConvertExampleElement;
        new (): HTMLBrowserVideoConvertExampleElement;
    };
    interface HTMLElementTagNameMap {
        "browser-video-convert-example": HTMLBrowserVideoConvertExampleElement;
    }
}
declare namespace LocalJSX {
    interface BrowserVideoConvertExample {
        "framePosition"?: 'start' | 'middle' | 'end' | number;
        "videoSrc"?: string|undefined;
    }
    interface IntrinsicElements {
        "browser-video-convert-example": BrowserVideoConvertExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "browser-video-convert-example": LocalJSX.BrowserVideoConvertExample & JSXBase.HTMLAttributes<HTMLBrowserVideoConvertExampleElement>;
        }
    }
}
